# Generated by Django 5.1.5 on 2026-06-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_order_referral_code_product_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_text', models.TextField(default='Limited Offer: Get 20% off all tech products using coupon code COLLABO20')),
                ('ticker_coupon_highlight', models.CharField(default='COLLABO20', max_length=50)),
                ('hero_badge_text', models.CharField(default='Curated Digital Marketplace', max_length=100)),
                ('hero_headline', models.CharField(default='Architectural Utility & Style', max_length=200)),
                ('hero_subheadline', models.TextField(default='Premium goods and tech gear handpicked by leading designers. Balanced aesthetics for your workspace, fashion, and lifestyle.')),
                ('hero_cta_primary', models.CharField(default='Browse Catalog', max_length=60)),
                ('hero_cta_secondary', models.CharField(default='Product Spotlight', max_length=60)),
                ('category_images', models.JSONField(blank=True, default=dict, help_text='Map of category name to background image URL. e.g. {"Electronics": "https://..."}')),
                ('deals_product_ids', models.JSONField(blank=True, default=list, help_text='List of product IDs to show in Deals of the Day (up to 4)')),
                ('trending_product_ids', models.JSONField(blank=True, default=list, help_text='List of product IDs to show in Trending section (up to 4)')),
                ('coupon_codes', models.JSONField(blank=True, default=list, help_text='List of {code, discount_percent, description} objects')),
                ('testimonials', models.JSONField(blank=True, default=list, help_text='List of {name, title, rating, text} testimonial objects')),
                ('footer_tagline', models.TextField(default='Designed for visual excellence and premium utility. Inspired by modern SaaS platforms.')),
                ('copyright_text', models.CharField(default='© 2026 CollaboCart Marketplace Inc. All rights reserved.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
