# Generated by Django 5.1.5 on 2026-06-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_referralclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral_map',
            field=models.JSONField(blank=True, default=dict, help_text='Per-product referral codes: {product_id: referral_code}'),
        ),
    ]
