# Generated by Django 5.1.5 on 2026-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order_referral_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='custom_commission_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Override influencer commission percent for this specific link', null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='custom_discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Override buyer discount percent for this specific link', null=True),
        ),
    ]
