# Generated by Django 5.1.5 on 2026-06-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_add_custom_rates_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='image',
            field=models.TextField(blank=True, default='', help_text='Review image URL or base64 data'),
        ),
    ]
