# Generated by Django 5.1.5 on 2026-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_add_image_to_customer_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='hero_card_carousel_enabled',
            field=models.BooleanField(default=False, help_text='Enable auto-sliding carousel on the hero bento card'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_card_slides',
            field=models.JSONField(blank=True, default=list, help_text='List of {title, subtitle, label, rating, image} slide objects for the hero card'),
        ),
    ]
