# Generated by Django 5.1.5 on 2026-06-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_hero_card_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage buyers get when purchasing via an influencer link'),
        ),
    ]
