# Generated by Django 5.1.5 on 2026-06-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_add_link_discount_percent_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(default=1500, help_text='Order subtotal (INR) above which shipping is free'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='shipping_charge',
            field=models.PositiveIntegerField(default=99, help_text='Flat shipping fee in INR charged per order'),
        ),
    ]
