# Generated by Django 5.1.5 on 2026-06-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_productreview_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='trending_phones_product_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of product IDs to feature in Trending Phones. Leave empty to auto-show all Mobiles.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='trending_phones_subtitle',
            field=models.CharField(default='MOBILES', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='trending_phones_title',
            field=models.CharField(default='Trending Phones', max_length=100),
        ),
    ]
