# Generated by Django 5.1.5 on 2026-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_order_cancel_comment_order_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of attachment URLs submitted with cancellation'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 Collabo Marketplace Inc. All rights reserved.', max_length=200),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='hero_badge_text',
            field=models.CharField(default='✨ YOUR ALL-IN-ONE MARKETPLACE', max_length=100),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='hero_headline',
            field=models.CharField(default='Premium Tech, Fashion & Daily Essentials', max_length=200),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='hero_subheadline',
            field=models.TextField(default='Explore high-quality electronics, trendsetting apparel, and essential home goods handpicked for your lifestyle. High quality, great deals.'),
        ),
    ]
