# Generated by Django 5.1.5 on 2026-06-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_order_delivery_notifications'),
        ('ecommerce', '0017_add_cancel_attachments'),
    ]

    operations = [
    ]
