# Generated by Django 5.1.5 on 2026-06-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_add_order_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_shipment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
