# Generated by Django 5.1.5 on 2026-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_add_shiprocket_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent_to_partner',
            field=models.BooleanField(default=False, help_text='Indicates if order details were sent to partner/seller'),
        ),
    ]
