# Generated by Django 5.1.5 on 2026-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_order_sent_to_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='serviceable_pincodes',
            field=models.JSONField(blank=True, default=list, help_text='List of deliverable PIN codes. Empty = deliver everywhere.'),
        ),
    ]
