# Generated by Django 5.1.5 on 2026-06-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_add_serviceable_pincodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of highlights'),
        ),
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.JSONField(blank=True, default=list, help_text='List of offers'),
        ),
        migrations.AddField(
            model_name='product',
            name='qa_section',
            field=models.JSONField(blank=True, default=list, help_text="List of Q&A [{q: '', a: ''}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_info',
            field=models.TextField(blank=True, help_text='Seller information and policies'),
        ),
    ]
