# Generated by Django 5.1.5 on 2026-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='promo_cards',
            field=models.JSONField(blank=True, default=list, help_text='List of {badge, title, subtitle, cta, category, bg} promo card objects for the category section sidebar'),
        ),
    ]
