# Generated by Django 5.1.5 on 2026-06-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_storesettings_promo_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping charge for this product in INR. 0 means free shipping.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(default=500, help_text='Order subtotal (INR) above which shipping is free'),
        ),
    ]
