# Generated by Django 5.1.5 on 2026-07-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
