# Generated by Django 5.1.5 on 2026-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='affiliate_benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of benefit strings'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='affiliate_headline',
            field=models.TextField(default='Share Products.\nEarn Real Money.\nEvery Single Day.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='affiliate_social_proof',
            field=models.CharField(default='2,400+ creators already earning with Collabo', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='affiliate_stats',
            field=models.JSONField(blank=True, default=list, help_text='List of {value, label} objects'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='affiliate_tagline',
            field=models.CharField(default="India's Fastest Growing Affiliate Program", max_length=200),
        ),
    ]
