# Generated by Django 5.1.5 on 2026-07-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_address_district'),
    ]

    operations = [
        # Fields were never added to the live DB (migration 0032 was local-only),
        # so no removal is needed here — this migration is intentionally empty.
    ]
