# Generated by Django 5.1.5 on 2026-07-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_storesettings_affiliate_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_benefits',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_headline',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_social_proof',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_stats',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_tagline',
        ),
    ]
