# Generated by Django 5.1.5 on 2026-07-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_storesettings_affiliate_benefits_and_more'),
        ('ecommerce', '0035_remove_order_delivery_otp'),
    ]

    operations = [
    ]
