# Generated by Django 5.1.5 on 2026-07-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_merge_20260713_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_benefits',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_headline',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_social_proof',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_stats',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='affiliate_tagline',
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='1=direct referrer, 2=upline (their recruiter)'),
        ),
    ]
