# Generated by Django 5.1.5 on 2026-07-14 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_wallettransaction_customerreferrallink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreferrallink',
            name='referred_via',
            field=models.ForeignKey(blank=True, help_text="Whoever's referral link (influencer or customer) this user came through for THIS product — the upline that earns half the wallet reward when this link converts. Captured at link creation time from the active referral code, independent of the account-level referred_by.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline_referral_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
