# Generated by Django 5.1.5 on 2026-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_walletpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpayout',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='walletpayout',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='walletpayout',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='walletpayout',
            name='bank_reference',
            field=models.CharField(blank=True, help_text='Admin-entered transaction/UTR reference once paid', max_length=200),
        ),
    ]
