# Generated by Django 5.1.5 on 2026-07-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0043_product_rejection_reason_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text="When the last 'you left something in your cart' WhatsApp reminder was sent for the cart's current contents. Reset (implicitly superseded) whenever updated_at moves past it, i.e. the cart changes again.", null=True),
        ),
    ]
