# Generated by Django 5.1.5 on 2026-07-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0045_cartitem_stable_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='show_deals_section',
            field=models.BooleanField(default=True, help_text='Show/hide the "Deals of the Day" section on the storefront homepage'),
        ),
    ]
