# Generated by Django 5.1.5 on 2026-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_storesettings_show_deals_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='deals_timer_hours',
            field=models.PositiveIntegerField(default=4, help_text='Duration in hours for the "Deals of the Day" countdown timer (recurring)'),
        ),
    ]
