# Generated by Django 5.1.5 on 2026-07-28 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0047_storesettings_deals_timer_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='deals_cycle_anchor',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Reference start time the recurring deals countdown cycles are calculated from. Reset to now whenever deals_timer_hours changes so the new duration takes effect immediately.'),
        ),
    ]
