# Generated by Django 5.1.5 on 2026-07-28 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0048_storesettings_deals_cycle_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='show_weekly_deals_section',
            field=models.BooleanField(default=True, help_text='Show/hide the "Weekly Best Deals" section on the storefront homepage'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='weekly_deals_cycle_anchor',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Reference start time the recurring Weekly Best Deals countdown cycles are calculated from. Reset to now whenever weekly_deals_timer_hours changes so the new duration takes effect immediately.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='weekly_deals_product_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of product IDs to show in Weekly Best Deals (up to 10)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='weekly_deals_timer_hours',
            field=models.PositiveIntegerField(default=168, help_text='Duration in hours for the "Weekly Best Deals" countdown timer (recurring)'),
        ),
    ]
