# Generated by Django 5.1.5 on 2026-08-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0049_storesettings_show_weekly_deals_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('return_policy', models.TextField(blank=True, default='')),
                ('delivery_time', models.CharField(default='Free delivery by Tomorrow', max_length=255)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ecommerce.vendor'),
        ),
    ]
