# Generated by Django 5.1.5 on 2026-08-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0050_vendor_product_return_policy_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text="List of color variants [{name: '', image: ''}]"),
        ),
    ]
