# Generated by Django 5.1.5 on 2026-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_approval_shown_alter_user_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('influencer', 'Influencer'), ('company', 'Company'), ('admin', 'Admin'), ('buyer', 'Buyer')], max_length=20),
        ),
    ]
