# Generated by Django 5.1.5 on 2026-06-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_buyer_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='cover_image',
            field=models.TextField(blank=True, help_text='Banner/cover image URL or base64 data'),
        ),
    ]
