# Generated by Django 5.1.5 on 2026-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.IntegerField(default=0, help_text='Accumulated customer reward points'),
        ),
    ]
