# Generated by Django 5.1.5 on 2026-06-16 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('influencer', 'Influencer'), ('company', 'Company'), ('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller')], max_length=20),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, unique=True)),
                ('tax_id', models.CharField(help_text='GSTIN / EIN / PAN', max_length=50)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(help_text='IFSC / Branch / Routing Code', max_length=50)),
                ('business_address', models.TextField()),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
