# Generated by Django 5.1.5 on 2026-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_user_type_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_document',
            field=models.TextField(blank=True, help_text='Base64 encoded bank document or URL'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='kyc_document',
            field=models.TextField(blank=True, help_text='Base64 encoded KYC document or URL'),
        ),
    ]
