# Generated by Django 5.1.5 on 2026-06-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_sellerprofile_bank_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_document_file',
            field=models.FileField(blank=True, null=True, upload_to='seller_kyc/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='kyc_document_file',
            field=models.FileField(blank=True, null=True, upload_to='seller_kyc/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='bank_document',
            field=models.TextField(blank=True, help_text='Deprecated: base64 encoded bank document'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='kyc_document',
            field=models.TextField(blank=True, help_text='Deprecated: base64 encoded KYC document'),
        ),
    ]
