# Generated by Django 5.1.5 on 2026-07-13 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sellerprofile_bank_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliate_code',
            field=models.CharField(blank=True, help_text='Unique code for recruiting other affiliates', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Who recruited this user as an affiliate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline', to=settings.AUTH_USER_MODEL),
        ),
    ]
