# Generated by Django 5.1.5 on 2026-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_affiliate_code_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_bank_ifsc',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
