# Generated by Django 5.1.5 on 2026-07-16 09:47

import django.contrib.auth.validators
from django.db import migrations, models


def blank_phones_to_null(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(phone='').update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_wallet_bank_account_name_and_more'),
    ]

    operations = [
        # Allow null first (column still NOT NULL otherwise) so the blank
        # values below can actually be nulled out before the unique
        # constraint is added — multiple users currently share phone=''.
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(blank_phones_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
