import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'influencer_platform.settings')
django.setup()

from django.contrib.auth import get_user_model
from ecommerce.models import Product

User = get_user_model()

seller = User.objects.filter(is_superuser=True).first()
if not seller:
    seller = User.objects.first()
if not seller:
    seller = User.objects.create_user(
        username='admin_seller',
        email='admin@collabo.com',
        password='adminpassword123',
        user_type='admin',
        is_staff=True,
        is_superuser=True
    )

print(f"Using seller user: {seller.username} ({seller.email})")

PRODUCTS_DATA = [
    {
        'name': 'Digital Kitchen Scale 10 Kg – Precision Weighing',
        'category': 'Home & Kitchen',
        'brand': 'DeoDap',
        'price': 269,
        'discount_price': 269,
        'rating': 4.50,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/products/03_6b0a2503-8b86-48ce-9c70-b363cdc1fcf8.jpg?v=1737629208&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/products/03_6b0a2503-8b86-48ce-9c70-b363cdc1fcf8.jpg?v=1737629208&width=1100',
            'https://deodap.in/cdn/shop/products/01_f4160401-2e36-4f1e-9cf9-4e3fb7228382.jpg?v=1737629208&width=1100',
            'https://deodap.in/cdn/shop/products/04_c9e765b2-f1b1-4c5f-8e8c-28bc6417f456.jpg?v=1737629208&width=1100',
            'https://deodap.in/cdn/shop/products/07_d01dba7a-d121-461d-83a6-acd14b56a45a.jpg?v=1737629208&width=600',
            'https://deodap.in/cdn/shop/products/02_cfb55325-75d7-4d81-bac9-207f1724f21c.jpg?v=1737629208&width=600',
        ],
        'description': 'High Precision Weighing: Equipped with an advanced High Precision Strain Gauge Sensor System, our scale delivers accurate readings down to 1 gram, ensuring your ingredients are measured precisely for consistent results every time.\n\nTare Functionality: Simplify your cooking with the convenient TARE option. Easily weigh multiple ingredients in the same container by subtracting the weight of the bowl, perfect for complex recipes and efficient meal prep.\n\nGenerous 10 Kg Capacity: From delicate spices to larger quantities of flour or vegetables, this versatile kitchen scale handles weights up to 10 kilograms, catering to all your culinary and household needs.\n\nDurable & Easy to Clean: Featuring a large, round stainless steel washable tray, this scale is built for durability and hygiene. Its splash-proof design makes it suitable for busy kitchen environments and ensures effortless cleanup after use.\n\nUser-Friendly Operation: Designed for simplicity, this battery-operated digital kitchen scale is incredibly easy to use with its clear display and intuitive controls, making it a valuable addition to any home.',
        'stock': 50,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            'High Precision Strain Gauge Sensor System - accurate to 1 gram',
            'Tare Functionality for weighing multiple ingredients',
            'Generous 10 Kg capacity',
            'Stainless steel washable tray, splash-proof design',
            'Battery-operated with clear display',
        ],
        'specifications': [
            {'name': 'Capacity', 'value': '10 Kg'},
            {'name': 'Precision', 'value': '1 gram'},
            {'name': 'Tray Material', 'value': 'Stainless Steel'},
            {'name': 'Power', 'value': 'Battery Operated'},
        ],
    },
    {
        'name': 'Electric Vegetable Cutter',
        'category': 'Home & Kitchen',
        'brand': 'DeoDap',
        'price': 549,
        'discount_price': 549,
        'rating': 4.40,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/products/01_e15a7a3c-5d62-4603-898a-902338549af7.jpg?v=1737634738&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/products/01_e15a7a3c-5d62-4603-898a-902338549af7.jpg?v=1737634738&width=1100',
            'https://deodap.in/cdn/shop/products/02_305205ca-1a1e-4a28-a8ac-e188120b3d03.jpg?v=1737634738&width=1100',
            'https://deodap.in/cdn/shop/products/03_0060e9a3-9ca7-445d-b806-01e27a71508e.jpg?v=1737634738&width=1100',
            'https://deodap.in/cdn/shop/products/10_909306b2-b527-44a2-8a14-24ca36756ce0.jpg?v=1737634738&width=600',
            'https://deodap.in/cdn/shop/products/04_2dd722af-8305-4b37-88ed-d96a94ee2a67.jpg?v=1737634738&width=600',
        ],
        'description': 'Multifunctional 4-in-1 Design: Chops, slices, dices, and prepares a wide range of vegetables and fruits with ease, acting as a complete handheld food chopper.\n\nErgonomic & Comfortable Grip: Designed for maximum comfort, reducing hand fatigue during extended use, perfect for daily kitchen tasks.\n\nEffortless One-Key Cleaning: Features a smart self-cleaning function where the whole machine can be rinsed under running water for quick and hygienic maintenance.\n\nPortable & Space-Saving: Lightweight and compact, making it easy to store and ideal for small kitchens or for those who value convenience.\n\nConvenient Filling Hole: Easily add ingredients like garlic, ginger, or chillies directly through the top without needing to open or unscrew the cap.\n\nDurable Blades: Crafted with high-quality, sharp blades for precise and consistent chopping and slicing.',
        'stock': 40,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            'Multifunctional 4-in-1 Design: chops, slices, dices',
            'Ergonomic & Comfortable Grip',
            'Effortless One-Key Cleaning',
            'Portable & Space-Saving',
            'Convenient Filling Hole',
            'Durable high-quality sharp blades',
        ],
        'specifications': [
            {'name': 'Type', 'value': 'Electric Handheld Food Chopper'},
            {'name': 'Functions', 'value': '4-in-1 (Chop, Slice, Dice, Prepare)'},
            {'name': 'Cleaning', 'value': 'One-Key Self-Cleaning'},
        ],
    },
    {
        'name': 'Adjustable Laptop Stand – Ergonomic Foldable Aluminum Design',
        'category': 'Gadgets & Electronics',
        'brand': 'DeoDap',
        'price': 299,
        'discount_price': 299,
        'rating': 4.60,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/01_98c0fe0f-78d9-450d-8e7a-4603e7e652b3.jpg?v=1739960096&width=990',
        'images': [
            'https://deodap.in/cdn/shop/files/01_98c0fe0f-78d9-450d-8e7a-4603e7e652b3.jpg?v=1739960096&width=990',
            'https://deodap.in/cdn/shop/files/02_06784475-c013-4611-aafd-2e86750c52da.jpg?v=1739960096&width=1100',
            'https://deodap.in/cdn/shop/files/fe326024-8080-4339-93a5-b3db40c3ac52.jpg?v=1739960096&width=1100',
            'https://deodap.in/cdn/shop/files/03_ac227702-7680-4cb1-8a5a-008537b5bf7a.jpg?v=1739960096&width=600',
            'https://deodap.in/cdn/shop/files/04_00e27095-ad63-4893-8455-75246bccdd8a.jpg?v=1739960096&width=600',
        ],
        'description': 'Ergonomic design reduces neck, back, and wrist strain.\n\nSix adjustable angles for ideal viewing height and posture.\n\nDurable aluminum construction with silicone rubber pads for stability.\n\nImproves airflow to protect laptops from overheating.\n\nCompact and foldable for easy portability and storage.\n\nCompatible with all laptops and MacBooks.\n\nLightweight at only 308g for effortless carrying.',
        'stock': 60,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            'Ergonomic design reduces neck, back, and wrist strain',
            'Six adjustable angles for ideal viewing height',
            'Durable aluminum construction with silicone rubber pads',
            'Improves airflow to protect laptops from overheating',
            'Compact and foldable for easy portability',
            'Compatible with all laptops and MacBooks',
            'Lightweight at only 308g',
        ],
        'specifications': [
            {'name': 'Material', 'value': 'Aluminum'},
            {'name': 'Weight', 'value': '308g'},
            {'name': 'Adjustable Angles', 'value': '6'},
            {'name': 'Compatibility', 'value': 'All Laptops & MacBooks'},
        ],
    },
    {
        'name': 'LED Toilet Bowl Light – Motion Sensor, 8 Colours | Indo Glow',
        'category': 'Home & Living',
        'brand': 'Indo Glow',
        'price': 259,
        'discount_price': 259,
        'rating': 4.30,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/b0d83b02-7861-46f5-aea9-389075508e02.jpg?v=1737616828&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/files/b0d83b02-7861-46f5-aea9-389075508e02.jpg?v=1737616828&width=1100',
            'https://deodap.in/cdn/shop/files/01_523ba3ed-33ba-4511-b3c6-1d05de13491e.jpg?v=1737616828&width=1100',
            'https://deodap.in/cdn/shop/files/04_01e2b232-00d9-462f-8809-a29fbee3deb7.jpg?v=1737616828&width=600',
        ],
        'description': 'Motion-Activated Sensor: Automatically turns on when you approach and off when you leave, conserving battery life and providing hands-free operation.\n\n8 Vibrant LED Colours: Choose from a spectrum of 8 distinct colours or set it to a rotating carousel mode to add a unique ambiance to your bathroom.\n\nUniversal & Easy Installation: Designed with a sturdy yet flexible arm that securely fits any toilet bowl rim in seconds, no tools required.\n\nBattery Operated: Powered by 3x AAA batteries (not included), ensuring cordless convenience and easy placement without electrical wiring.\n\nDurable & Splash-Proof: Constructed for long-lasting performance in a bathroom environment, offering reliability and peace of mind.\n\nEnhanced Night-Time Safety: Prevents trips and falls in the dark, making it safer for children, the elderly, and anyone needing a subtle guide at night.',
        'stock': 35,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            'Motion-Activated Sensor for hands-free operation',
            '8 Vibrant LED Colours with rotating carousel mode',
            'Universal & Easy Installation, no tools required',
            'Battery Operated (3x AAA, not included)',
            'Durable & Splash-Proof',
            'Enhanced Night-Time Safety',
        ],
        'specifications': [
            {'name': 'LED Colours', 'value': '8'},
            {'name': 'Sensor', 'value': 'Motion-Activated'},
            {'name': 'Power', 'value': '3x AAA Batteries (not included)'},
            {'name': 'Installation', 'value': 'Tool-free, flexible arm'},
        ],
    },
    {
        'name': 'Bladeless Neck Fan – USB Rechargeable & Hands-Free | DeoDap',
        'category': 'Cooling Gadgets',
        'brand': 'DeoDap',
        'price': 449,
        'discount_price': 449,
        'rating': 4.50,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/01_8e168b7f-882e-4f0c-8215-cf948f36ede7.jpg?v=1752475858&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/files/01_8e168b7f-882e-4f0c-8215-cf948f36ede7.jpg?v=1752475858&width=1100',
            'https://deodap.in/cdn/shop/files/2092621445_124ae048-20be-450a-b9d7-fc5a9f039f5a.png?v=1767102564&width=600',
            'https://deodap.in/cdn/shop/files/2092621446_99c389f2-e824-42e4-8134-c682758d9973.png?v=1767102564&width=600',
            'https://deodap.in/cdn/shop/files/2092621447_a8c22f0c-3e16-4021-891a-bd9d72bcf10b.png?v=1767102564&width=600',
            'https://deodap.in/cdn/shop/files/03_f2975b6a-2ff5-4fee-81cf-ece23437b92d.jpg?v=1767102564&width=600',
        ],
        'description': 'Rapid & Efficient Cooling: Feel refreshed in just 3 seconds with multiplied wind power from 60 internal fan blades and 48 external air outlets.\n\nSafe & Hands-Free Design: Enjoy complete safety with a bladeless structure, preventing hair entanglement and making it ideal for all ages.\n\nLightweight & Comfortable: Fashionable, ergonomic design resembling headphones ensures comfortable, effortless wearing for hours.\n\nUSB Rechargeable Battery: Conveniently power up your portable personal fan via USB from laptops, power banks, or wall chargers, offering 2.4 to 8.5 hours of use.\n\nAdjustable Airflow: Choose from 3 distinct wind speeds to perfectly match your cooling needs, from a gentle breeze to a powerful gust.\n\nUltra-Quiet Operation: Designed for quiet performance, allowing you to focus on your activities without distracting fan noise.',
        'stock': 30,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            'Rapid cooling in just 3 seconds',
            'Safe bladeless design, no hair entanglement',
            'Lightweight & comfortable, headphone-style',
            'USB Rechargeable, 2.4 to 8.5 hours of use',
            '3 adjustable wind speeds',
            'Ultra-Quiet Operation',
        ],
        'specifications': [
            {'name': 'Fan Blades', 'value': '60 internal'},
            {'name': 'Air Outlets', 'value': '48 external'},
            {'name': 'Battery Life', 'value': '2.4 - 8.5 hours'},
            {'name': 'Charging', 'value': 'USB Rechargeable'},
            {'name': 'Speed Settings', 'value': '3'},
        ],
    },
    {
        'name': 'Rechargeable Kneading Neck & Shoulder Massager with Heat & Strap',
        'category': 'Health & Wellness',
        'brand': 'DeoDap',
        'price': 1799,
        'discount_price': 1799,
        'rating': 4.70,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/21_massager.jpg?v=1764064060&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/files/21_massager.jpg?v=1764064060&width=1100',
            'https://deodap.in/cdn/shop/files/17_massager.jpg?v=1764064060&width=1100',
            'https://deodap.in/cdn/shop/files/19_massager.jpg?v=1764064060&width=600',
            'https://deodap.in/cdn/shop/files/20_massager.jpg?v=1764064060&width=600',
        ],
        'description': 'Deep Kneading Action: Flexible finger-pressure nodes target stubborn knots for effective muscle relaxation.\n\nSoothing Heat Therapy: Selectable heating function boosts circulation & eases muscle fatigue.\n\nCustomizable Comfort: Adjustable strap ensures a perfect fit for your neck, shoulders, back, waist, or legs.\n\nEffortless Control: Simple dual-button interface for quick massage & heat adjustments.\n\nPortable & Convenient: Lightweight design means relief is always at hand, whether at home, the office, or traveling.\n\nInstant Relief: Effectively reduces stiffness, tension, fatigue, & general muscle discomfort.',
        'stock': 20,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            'Deep Kneading Action with finger-pressure nodes',
            'Soothing Heat Therapy for circulation',
            'Adjustable strap for neck, shoulders, back, waist, or legs',
            'Simple dual-button interface',
            'Portable & Lightweight',
            'Instant relief from stiffness, tension & fatigue',
        ],
        'specifications': [
            {'name': 'Type', 'value': 'Kneading Massager with Heat'},
            {'name': 'Power', 'value': 'Rechargeable'},
            {'name': 'Controls', 'value': 'Dual-Button Interface'},
            {'name': 'Suitable For', 'value': 'Neck, Shoulders, Back, Waist, Legs'},
        ],
    },
    {
        'name': 'Smart Electric Scalp & Body Massager with 4 Heads',
        'category': 'Personal Care',
        'brand': 'DeoDap',
        'price': 549,
        'discount_price': 549,
        'rating': 4.50,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/SmartScalpMassager-01.jpg?v=1777956646&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/files/SmartScalpMassager-01.jpg?v=1777956646&width=1100',
            'https://deodap.in/cdn/shop/files/SmartScalpMassager-size.jpg?v=1777956646&width=1100',
            'https://deodap.in/cdn/shop/files/SmartScalpMassager-02.jpg?v=1777956646&width=493',
            'https://deodap.in/cdn/shop/files/SmartScalpMassager-04.jpg?v=1777956646&width=493',
        ],
        'description': 'Versatile Relief: Features 4 detachable massage heads for targeted comfort on various body areas.\n\nGentle & Safe: Soft silicone bristles ensure no hair pulling or tangling, making it perfect for all hair types.\n\nLong-Lasting Power: Rechargeable via USB, providing up to 1 week of use on a single charge for ultimate convenience.\n\nWet & Dry Use: IPX6 waterproof rating allows for relaxing massages in the shower or bath.\n\nErgonomic Design: Lightweight & comfortable to hold, ensuring a relaxing experience without hand fatigue.\n\nSmart Safety: Auto shut-off after 10 minutes prevents overuse & conserves battery.',
        'stock': 25,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            '4 detachable massage heads',
            'Soft silicone bristles, no hair pulling',
            'USB Rechargeable, up to 1 week on single charge',
            'IPX6 waterproof - wet & dry use',
            'Lightweight & ergonomic design',
            'Auto shut-off after 10 minutes',
        ],
        'specifications': [
            {'name': 'Massage Heads', 'value': '4 Detachable'},
            {'name': 'Waterproof Rating', 'value': 'IPX6'},
            {'name': 'Battery Life', 'value': 'Up to 1 week'},
            {'name': 'Charging', 'value': 'USB Rechargeable'},
            {'name': 'Auto Shut-off', 'value': '10 minutes'},
        ],
    },
    {
        'name': 'Electric Egg Boiler – 2 Layer Steamer & Poacher',
        'category': 'Kitchen',
        'brand': 'DeoDap',
        'price': 449,
        'discount_price': 449,
        'rating': 4.40,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/02_9e30ec62-ec6d-44d5-a90f-337fd45ed3f4.jpg?v=1751117264&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/files/02_9e30ec62-ec6d-44d5-a90f-337fd45ed3f4.jpg?v=1751117264&width=1100',
            'https://deodap.in/cdn/shop/files/005_8c2de21a-9d03-49c4-9015-52802fbc9a6c.jpg?v=1751117264&width=1100',
            'https://deodap.in/cdn/shop/files/3_88871b23-7ae9-4bed-b1f0-c00f464b0615.jpg?v=1751117263&width=600',
        ],
        'description': 'Efficient 2-Layer Design: Cook up to 7 eggs simultaneously, catering to family breakfasts or meal prep needs. The dual-layer allows for flexible cooking options.\n\nMulti-functional Appliance: Beyond boiling, use it as an efficient egg poacher or a handy steamer for vegetables, momos, or idlis, making it a true healthy breakfast solution.\n\nPrecision Cooking: Achieve perfect boiled eggs – soft, medium, or hard – with the included measuring cup that ensures the right water level and has a piercing pin to prevent shells from cracking.\n\nAutomatic Shut-off & Buzzer: No more overcooked eggs! The appliance automatically switches off with an audible buzzer once your eggs are ready, ensuring consistent results.\n\nFast & Energy-Saving: Boils eggs faster and more efficiently than traditional stovetop methods, saving you time and electricity.\n\nTransparent Lid: Monitor the cooking process easily through the crystal-clear top cover without lifting the lid.\n\nEasy to Clean: Removable egg trays and poaching tray make cleanup a breeze, ensuring hygiene and convenience after every use.\n\nSafe & Convenient: Comes with a tray lifting tool to safely handle hot eggs, preventing burns and making serving simple.',
        'stock': 30,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            'Cook up to 7 eggs simultaneously',
            'Multi-functional: boiler, poacher & steamer',
            'Precision cooking with measuring cup & piercing pin',
            'Automatic Shut-off & Buzzer',
            'Fast & Energy-Saving',
            'Transparent Lid for monitoring',
            'Easy to Clean with removable trays',
        ],
        'specifications': [
            {'name': 'Capacity', 'value': 'Up to 7 eggs'},
            {'name': 'Layers', 'value': '2'},
            {'name': 'Functions', 'value': 'Boiling, Poaching, Steaming'},
            {'name': 'Safety', 'value': 'Automatic Shut-off with Buzzer'},
        ],
    },
    {
        'name': 'Mini Nano Mist Sprayer - USB Rechargeable Portable Face Steamer',
        'category': 'Personal Care',
        'brand': 'DeoDap',
        'price': 299,
        'discount_price': 299,
        'rating': 4.30,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/1313-02-sku_ceca7234-471b-4781-b169-a00a01b6cbc1.jpg?v=1780995939&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/files/1313-02-sku_ceca7234-471b-4781-b169-a00a01b6cbc1.jpg?v=1780995939&width=1100',
            'https://deodap.in/cdn/shop/files/1313-03-product_cbdbe3df-dddf-47b8-9c00-2b4bdc7d4a9b.jpg?v=1780995939&width=1100',
            'https://deodap.in/cdn/shop/files/1313-07-product_47972df9-0b5f-4ea6-b0e4-f84c31cbab85.jpg?v=1780995939&width=600',
        ],
        'description': 'Instant Hydration: Delivers a fine nano mist that quickly absorbs, leaving skin feeling fresh & moisturized.\n\nFlawless Makeup: Helps set your makeup evenly for a long-lasting, natural finish.\n\nPortable & Convenient: Compact, lightweight, and USB rechargeable for on-the-go use – no messy batteries!\n\nVersatile Use: Fill with water or your favorite toner for personalized skincare.\n\nQuiet Operation: Enjoy a soothing mist without disturbance, ideal for office or travel.',
        'stock': 45,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            'Fine nano mist for instant hydration',
            'Helps set makeup for a long-lasting finish',
            'Compact, lightweight & USB rechargeable',
            'Fill with water or toner',
            'Quiet operation, ideal for office or travel',
        ],
        'specifications': [
            {'name': 'Type', 'value': 'Nano Mist Sprayer / Face Steamer'},
            {'name': 'Charging', 'value': 'USB Rechargeable'},
            {'name': 'Portability', 'value': 'Compact & Lightweight'},
        ],
    },
    {
        'name': 'Mini Bag Sealer – 2 in 1 Portable Heat Seal & Cutter',
        'category': 'Home & Kitchen',
        'brand': 'DeoDap',
        'price': 249,
        'discount_price': 249,
        'rating': 4.20,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/iZemxgyfUHZ3w7TDRpTGpb6j6QPUDEwzRro5KFsz.jpg?v=1776688485&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/files/iZemxgyfUHZ3w7TDRpTGpb6j6QPUDEwzRro5KFsz.jpg?v=1776688485&width=1100',
            'https://deodap.in/cdn/shop/files/3030315.webp?v=1776688485&width=1100',
            'https://deodap.in/cdn/shop/files/3030316.webp?v=1776688485&width=600',
            'https://deodap.in/cdn/shop/files/3030317.webp?v=1776688485&width=600',
        ],
        'description': '2 in 1 Seal & Cutter: Combines bag sealing and cutting functions, replacing clips and scissors.\n\nQuick Heat, No Preheat Needed: Ready to use within 10 seconds with fast heat-up time.\n\nRechargeable USB Type-C: Environment-friendly built-in battery with USB charging port.\n\nWide Compatibility: Works with plastic bags, polyester film bags, and vacuum bags.\n\nNot Suitable For: Cellophane bags, Kraft paper bags, aluminium bags, or very thin food storage bags.\n\nCompact & Portable: Small size ideal for home use or travel and easy to store.\n\nEnhances Food Freshness: Seals air-tight and extends shelf life of snacks and pet food.\n\nErgonomic Design: Easy-to-use push-button operation with hidden cutter to avoid extra devices.',
        'stock': 40,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            '2 in 1: Seal & Cutter in one device',
            'Quick Heat, ready in 10 seconds',
            'Rechargeable USB Type-C',
            'Works with plastic, polyester film & vacuum bags',
            'Compact & Portable for home or travel',
            'Seals air-tight to extend food freshness',
        ],
        'specifications': [
            {'name': 'Functions', 'value': 'Heat Seal & Cutter'},
            {'name': 'Heat-up Time', 'value': '10 seconds'},
            {'name': 'Charging', 'value': 'USB Type-C Rechargeable'},
            {'name': 'Compatible Bags', 'value': 'Plastic, Polyester Film, Vacuum'},
        ],
    },
    {
        'name': 'Electronics Cleaning Kit – 20-in-1 Multi-Device Tool',
        'category': 'Gadgets & Electronics',
        'brand': 'DeoDap',
        'price': 499,
        'discount_price': 499,
        'rating': 4.60,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/12908_20in1_multi_cleaner_kit.jpg?v=1752151437&width=990',
        'images': [
            'https://deodap.in/cdn/shop/files/12908_20in1_multi_cleaner_kit.jpg?v=1752151437&width=990',
            'https://deodap.in/cdn/shop/files/011_299b90fa-c7d5-451b-8927-7b1e64490778.jpg?v=1752151437&width=1100',
            'https://deodap.in/cdn/shop/files/07_487347d8-0316-4506-8206-d51872850761.jpg?v=1752151435&width=600',
            'https://deodap.in/cdn/shop/files/02_d931686a-513d-4386-9c6b-652eb247571a.jpg?v=1752151435&width=600',
            'https://deodap.in/cdn/shop/files/06_453fbad5-ace4-4a61-bfa8-563eeb44cce9.jpg?v=1752151435&width=600',
        ],
        'description': '20-in-1 Comprehensive Set: Includes a wide array of tools like retractable brushes, a specialized AirPods cleaning pen, screen cleaning spray, microfiber cloth, keycap extractor, and more.\n\nMulti-Device Compatibility: Perfectly suited for cleaning keyboards, laptops, smartphones, tablets, cameras, AirPods, and other electronic devices.\n\nEffective Screen Cleaning: Comes with an electronics screen cleaning spray and a high-quality microfiber cloth to effortlessly remove oils and fingerprints, leaving screens crystal clear.\n\nPrecision AirPods & Earbuds Cleaner: Features a metal clip, mini brush, and flocked sponge brush designed to reach and clean dirt hidden in charging ports, cracks, and speaker holes.\n\nErgonomic Keyboard Cleaning: Equipped with a retractable brush and keycap extractor for easy cleaning under keycaps and across desktop surfaces, ensuring your keyboard cleaner experience is efficient.\n\nPortable & Convenient: All tools are compactly stored in a portable kit, making it easy to carry and use wherever you go, ensuring your gadgets are always clean.',
        'stock': 35,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            '20-in-1 Comprehensive cleaning set',
            'Multi-Device: keyboards, laptops, phones, tablets, cameras, AirPods',
            'Screen cleaning spray & microfiber cloth included',
            'Precision AirPods & Earbuds cleaner tools',
            'Retractable brush & keycap extractor for keyboards',
            'Portable kit, easy to carry',
        ],
        'specifications': [
            {'name': 'Set Size', 'value': '20-in-1'},
            {'name': 'Includes', 'value': 'Brushes, Cleaning Pen, Spray, Microfiber Cloth, Keycap Extractor'},
            {'name': 'Compatible Devices', 'value': 'Keyboards, Laptops, Smartphones, Tablets, Cameras, AirPods'},
        ],
    },
    {
        'name': 'Solar Camping Light – USB Rechargeable Emergency LED',
        'category': 'Travel Accessories',
        'brand': 'DeoDap',
        'price': 549,
        'discount_price': 549,
        'rating': 4.50,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/20849.png?v=1764321035&width=600',
        'images': [
            'https://deodap.in/cdn/shop/files/20849.png?v=1764321035&width=600',
            'https://deodap.in/cdn/shop/files/ac3fe78f-64cc-4224-994f-4db47c131fcb.jpg?v=1764321035&width=1100',
            'https://deodap.in/cdn/shop/files/02_fb21a780-107e-4fb0-902f-01bd05a787b4.jpg?v=1764321035&width=600',
            'https://deodap.in/cdn/shop/files/20852.png?v=1764321035&width=600',
            'https://deodap.in/cdn/shop/files/04_2d3cc358-263c-4b7d-b5d8-c19de141266b.jpg?v=1764321035&width=600',
        ],
        'description': '45 Bright LED Beads: Provides powerful and widespread illumination, making it ideal for large areas.\n\nUSB Rechargeable 2400mAh Battery: Offers extended lighting hours and can be conveniently recharged via any USB port, ensuring continuous power.\n\nIntegrated Solar Charging: Harness the power of the sun to keep your Solar Camping Light charged, perfect for off-grid use and eco-conscious users.\n\nFive Versatile Brightness Modes: Easily switch between strong, medium, low, flicker, and an essential SOS mode for emergencies, adapting to any situation.\n\nIP65 Waterproof Rating: Built to withstand the elements, this durable light is protected against dust and water splashes, making it reliable in all weather conditions.\n\nFoldable & Compact Design: Its innovative foldable structure makes it incredibly easy to pack and carry, saving space in your backpack or emergency kit.\n\nConvenient Hanging Hooks: Equipped with sturdy hooks, you can easily hang this Solar Camping Light in tents, cars, or any overhead space for hands-free lighting.\n\nMulti-Purpose Utility: Perfect for camping, hiking, fishing, power outages, car repairs, and general outdoor exploration.',
        'stock': 25,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            '45 Bright LED Beads for powerful illumination',
            'USB Rechargeable 2400mAh Battery',
            'Integrated Solar Charging',
            '5 brightness modes including SOS',
            'IP65 Waterproof Rating',
            'Foldable & Compact with hanging hooks',
        ],
        'specifications': [
            {'name': 'LED Beads', 'value': '45'},
            {'name': 'Battery', 'value': '2400mAh USB Rechargeable'},
            {'name': 'Charging', 'value': 'USB + Solar'},
            {'name': 'Brightness Modes', 'value': '5 (Strong, Medium, Low, Flicker, SOS)'},
            {'name': 'Waterproof Rating', 'value': 'IP65'},
        ],
    },
    {
        'name': 'Electric Lint Remover USB Fabric Shaver with Cleaning Brush',
        'category': 'Home & Kitchen',
        'brand': 'DeoDap',
        'price': 499,
        'discount_price': 499,
        'rating': 4.30,
        'reviews_count': 0,
        'image': 'https://deodap.in/cdn/shop/files/Lint-Removal-002--07.jpg?v=1779178311&width=1100',
        'images': [
            'https://deodap.in/cdn/shop/files/Lint-Removal-002--07.jpg?v=1779178311&width=1100',
            'https://deodap.in/cdn/shop/files/LintRemoval002-02.jpg?v=1779178310&width=1100',
            'https://deodap.in/cdn/shop/files/LintRemoval002-04.jpg?v=1779178310&width=1100',
            'https://deodap.in/cdn/shop/files/LintRemoval002-03.jpg?v=1779178310&width=600',
            'https://deodap.in/cdn/shop/files/LintRemoval002-05.jpg?v=1779178310&width=600',
        ],
        'description': 'Electric lint remover for efficient fuzz & pill removal.\n\nUSB rechargeable for cordless daily use.\n\nCompact handheld design for easy grip & control.\n\nProtective shaving surface safeguards fabric.\n\nIncludes cleaning brush for hassle-free upkeep.\n\nIdeal for clothes, sweaters, blankets, curtains & sofas.\n\nLightweight and portable for home & travel.\n\nKeeps garments neat, smooth and presentable.',
        'stock': 30,
        'delivery': 'Free delivery by Tomorrow',
        'highlights': [
            'Efficient fuzz & pill removal',
            'USB Rechargeable for cordless use',
            'Compact handheld design',
            'Protective shaving surface safeguards fabric',
            'Includes cleaning brush',
            'Ideal for clothes, sweaters, blankets, curtains & sofas',
            'Lightweight and portable',
        ],
        'specifications': [
            {'name': 'Type', 'value': 'Electric Lint Remover / Fabric Shaver'},
            {'name': 'Charging', 'value': 'USB Rechargeable'},
            {'name': 'Accessories', 'value': 'Cleaning Brush included'},
            {'name': 'Suitable For', 'value': 'Clothes, Sweaters, Blankets, Curtains, Sofas'},
        ],
    },
]

created_count = 0
for prod_data in PRODUCTS_DATA:
    if not Product.objects.filter(name=prod_data['name']).exists():
        Product.objects.create(seller=seller, **prod_data)
        created_count += 1
        print(f"  Created: {prod_data['name']} - INR {prod_data['price']}")
    else:
        print(f"  Skipped (already exists): {prod_data['name']}")

print(f"\nSuccessfully populated {created_count} new DeoDap products!")
