# Generated by Django 5.1.5 on 2026-06-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('payment', 'Payment'), ('campaign', 'Campaign'), ('account', 'Account'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=20),
        ),
    ]
